/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EECS3311.Project;

/**
 * @author Nourin Abd El Hadi
 *
 */

public class Library {
	public boolean someLibraryMethod() {
		return true;
	}
}
